# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: 'junit.xml'
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: create new release
      id: create_new_release_version
      run: |
        docker image build -t cloud-native-seminar .
        docker image tag cloud-native-seminar licheng5625/cloud-native-seminar
        docker image push licheng5625/cloud-native-seminar
    - uses: Azure/k8s-set-context@v2
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        namespace: licheng5625
        manifests: |
            node-app-deployment.yaml