
name: deploy

on:
  push:
    branches: [ "3/k8s" ]

jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/k8s-set-context@v2
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        namespace: licheng5625
        manifests: |
            node-app-deployment.yaml
